/******************************************************************************
 *  \file ___FILENAME___
 *  \author ___FULLUSERNAME___
 *  \date ___DATE___
 *  \class ___FILEBASENAMEASIDENTIFIER___
 *  \brief <#BRIEF#>
 *  \details from https://github.com/amattn/RealLifeXcode4Templates
 *  \abstract NSManagedObject subclass.  Encapsulated functionality specific to 
 *            a given Core Data Entity. 
 *  \copyright Copyright ___ORGANIZATIONNAME___ ___YEAR___. All rights reserved.
 */

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
___COREDATAMANAGEDOBJECTSUPERCLASSIMPORT___

#pragma mark ** Constant Defines **

#pragma mark ** Protocols & Declarations **

___COREDATAMANAGEDOBJECTCLASSREFERENCES___

@protocol ___FILEBASENAMEASIDENTIFIER___GeneratedAccessors
// If you need public access to the autogenerated relationship
// accessors in the .m, you can declare them here.
@end

@interface ___FILEBASENAMEASIDENTIFIER___ : ___COREDATAMANAGEDOBJECTSUPERCLASS___ <___FILEBASENAMEASIDENTIFIER___GeneratedAccessors>
{
    
}

#pragma mark ** Custom Properties **

#pragma mark ** Methods **

#pragma mark ** Core Data Properties **

___COREDATAPROPERTYDECLARATIONS___

@end
