/******************************************************************************
 * - Created ___DATE___ by ___FULLUSERNAME___
 * - Copyright ___ORGANIZATIONNAME___ ___YEAR___. All rights reserved.
 * - License: <#LICENSE#>
 *
 * NSManagedObject subclass.  Encapsulated functionality specific to a given 
 * Core Data Entity
 *
 * Created from templates: https://github.com/amattn/RealLifeXcode4Templates
 */

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>
___COREDATAMANAGEDOBJECTSUPERCLASSIMPORT___

#pragma mark ** Constant Defines **

#pragma mark ** Protocols & Declarations **

___COREDATAMANAGEDOBJECTCLASSREFERENCES___

@protocol ___FILEBASENAMEASIDENTIFIER___GeneratedAccessors
// If you need public access to the autogenerated relationship
// accessors in the .m, you can declare them here.
@end

@interface ___FILEBASENAMEASIDENTIFIER___ : ___COREDATAMANAGEDOBJECTSUPERCLASS___ <___FILEBASENAMEASIDENTIFIER___GeneratedAccessors>
{
    
}

#pragma mark ** Custom Properties **

#pragma mark ** Methods **

#pragma mark ** Core Data Properties **

___COREDATAPROPERTYDECLARATIONS___

@end
